### PR TITLE
Harmonize SecConfigs all 5 MSs + Fix for Swagger-UI MS Studies #289

### PR DESCRIPTION
**Pull request by michaelkain**
- corrects the swagger UI for preclinical also -> now displayed too
- removes Swagger2Enabled from ms users to better protect the interface

### CODE REVIEW

**Comment by michaelkain** [comment]
Hi Jean-Come, could you please verify this PR? The most important test is, that it runs up, e.g. with bootstrap.sh and that all microservices are accessible using the GUI. It would be great to verify too, that all 4 swagger URLs (studies, import, preclinical, datasets) are now accessible and display the methods.

**Comment by jcomedouteau** [comment]
Sure !

**Comment by michaelkain** [comment]
I updated the README.md for the REST-URLs.

**Comment by michaelkain** [comment]
Great, thank you!

**Comment by jcomedouteau** [comment]
@michaelkain I have some problem accessing to swagger interfaces.

When I go to shanoir-ng-nginx/shanoir-ng/studies/ for example, I am redirected to
http://shanoir-ng-nginx/swagger-ui.html
(and not https, which is quite important no?)

And I have this error in my network toolbar:
> (failed)net::ERR_CONNECTION_REFUSED

I think I should be redirected to 
https://shanoir-ng-nginx/shanoir-ng/studies/swagger-ui.html
which is the adapted endpoint where I can actually find the swagger UI

For the rest, bootstrap.sh is running well and I have access to all containers.

**Comment by michaelkain** [comment]
Hi Jean-Come, as I am quite busy at the moment, I am happy, if swagger is working for studies and preclinical ms, and removed for ms users. So, as long as the deep links work, I am fine with it, and they are linked from all GitHub docs too, so I will merge the pull request. We could optimise it later. With kind regards, Michael

**Comment by jcomedouteau** [comment]
Fine for me too, links are working

**Pull request merged**
