### PR TITLE
Export from subject (or any bids element) and sort bids tree.

### PR DESCRIPTION
**Pull request by jcomedouteau**

### CODE REVIEW

**Comment by jcomedouteau** [comment]
+ correct BIDS import

**Comment by Nunien** [comment]
* I have a problem with the import : 
Capture d’écran de 2020-09-18 13-17-13

* I can't see any download button in subject pages
* The button works well in study

**Comment by jcomedouteau** [comment]
I sent you an email with a correct archive that you can try to play with.
Should I add a button on subject's side you think ?

**Comment by Nunien** [comment]
> I sent you an email with a correct archive that you can try to play with.

I got the zip, thank you.

> Should I add a button on subject's side you think ?

I don't know but that's in the todos of https://github.com/fli-iam/shanoir-ng/issues/466

**Comment by jcomedouteau** [comment]
That's right, I was wondering if it's a good idea, if the subjects takes part in multiple studies it may complicate things. => In that case we may have to choose one linked study.

**Comment by Nunien** [comment]
@jcomedouteau No problemo.
I have a problem with that new bids zip : 
Capture d’écran de 2020-09-18 14-54-12

**Comment by jcomedouteau** [comment]
Mmm I think you have to open the archive to change /sourceData/sub-bidsCreated/import-shanoir.json to adapt studyCardId with studyId.

**Comment by Nunien** [comment]
That worked ! 
But I have no "next" button : 
Capture d’écran de 2020-09-18 15-04-18

**Comment by jcomedouteau** [comment]
Yes, I was thinking of going to a new page where the bids structure imported is displayed, but this is not the point of this PR.

**Review by Nunien — APPROVED** [review]

**Pull request merged**
