### PR TITLE
Shanoir issue#1196 Display center list in study detail (+prefix)

### LINKED ISSUE #1196: View study: center list + prefixes are not displayed (only in edit study)

### PR DESCRIPTION
**Pull request by jcomedouteau**
Open a study
Add multiple centers
Add subject study prefix for some centers
Check the detail visual -> You can now view the centers and their associated prefix.

Closes #1196

### CODE REVIEW

**Comment by jcomedouteau** [comment]
Visuel:
image

**Comment by michaelkain** [comment]
Hi Jean-Come, I start to test it on my local machine. Cheers, Michael

**Comment by jcomedouteau** [comment]
The front is quite "simple", maybe Julien can do something about it :)

**Review by michaelkain — APPROVED** [review]
I tested locally, and it works fine.

**Comment by michaelkain** [comment]
Hi Jean-Come, thank you, it works really good.
The GUI is fully okay, better than displaying nothing today, if Julien wants to optimise it,
no worries, it could be integrated into his PR, where he puts the different parts of edit study
into multiple areas (tabs/screens), but the feature is already there at least. Cheers, Michael

**Pull request merged**
