### PR TITLE
tree view v1

### PR DESCRIPTION
**Pull request by julien-louis**

### CODE REVIEW

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne the commit names speak for themself but here is the list of bugs/improvements I done :
* alphabetic subjects order in tree (+using back former labeling) 
* removed tree tab in study
* subject role (can't remember what this is)
* independent scrolls between tree and details
* metadata to metadata was buggy
* check tree nodes menu options are now available in the details side 
    * reverse study : dl
    * subject : dl
    * exam : view in ohif / dl / delete
    * acq : dl / delete
    * ds : dl / delete
    * process : delete
    * studycard : delete
* details boutons are now at the top
* when delete a node -> go to the parent element
* buttons related to selected datasets in tree are now at the top of the tree
* home : ellipsis fixed
* list -> new -> bug fixed
* home icons don't go to line : fixed

**Comment by pierrehenri-dauvergne** [comment]
Small CSS issue on "new subject" page:
image

Error: "TypeError: examination.study is undefined" when opening new examination/center/acquisition equipment/study card/quality card.

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne  done

**Comment by pierrehenri-dauvergne** [comment]
Some issues remains: 
- There are issues when opening the "acquisition center" list page, error in network tab: "failed to lazily initialize a collection of role: org.shanoir.ng.center.model.Center.studyCenterList: could not initialize proxy - no Session"
- "TypeError: examination.study is undefined" when opening the "new" from examination list page

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne I fixed the listed bugs

**Comment by pierrehenri-dauvergne** [comment]
- When I try to create a new Exam, I get this error: "Cannot invoke "org.shanoir.ng.shared.model.Subject.getId()" because the return value of "org.shanoir.ng.examination.model.Examination.getSubject()" is null"
- When I open "center equipment" page, I get this error: "failed to lazily initialize a collection of role: org.shanoir.ng.center.model.Center.studyCenterList: could not initialize proxy - no Session"
- Just wondering what happens when a subject belongs to multiple studies. If I open this subject, how do we decide which study tree to show ? Example, "subject" belongs to "Study1" and "CopiedDatasets". If I open Study1 then subject, I have the Study1's tree. Then if I open CopiedDataset then subject, I have the CopiedDataset's tree.


image
image

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne 
* I fixed the bugs
* About subjects in multiple studies : we have decided to leave it as it is (the first study found is used) because soon a subject may be allowed only in one single study.

**Comment by pierrehenri-dauvergne** [comment]
- I created an exam, then updated its date and comment but the tree view wasn't updated with the new infos:
image

- When I create a new acquisition center, after saving, I'm redirected to the "view center" page with a tree view that is not related to the center I just created. Shouldn't I be redirected to the center list? The same thing happens when creating a new acquisition equipment/coils/preclinical pathologies, therapies, anesthetics. Maybe for objects that are not directly related to a study and can exist by themselves we should not display the tree view after creation?
image

- When creating a new study card, I get this error in console: "this.studyNode.studyCardsNode.cards.find is not a function" even though the study card was correctly created. Same error when creating a new quality card: "TypeError: this.studyNode.qualityCardsNode.cards.find is not a function"

- When opening an existing preclinical-subject, I get this error: "this.input.subject is undefined"

- When opening a preclinical examination, I get this error: "NoResourceFoundException: No static resource examination/25."

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne I think it's ok.

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne I couln't reproduce the two null pointer exceptions, the rest is fixed

**Review by pierrehenri-dauvergne — APPROVED** [review]

**Pull request merged**
