### PR TITLE
Tree updates

### PR DESCRIPTION
**Pull request by julien-louis**
see https://github.com/fli-iam/shanoir-ng/issues/2392

List of demands : 
* slider because ican subjects too long [OK]
* buttons visible [OK]
* open by default [OK]
* text filter [OK]
* unselect all ? [OK]
* refresh tree when deleting from a list (i.e. acquisition) [OK]

### CODE REVIEW

**Comment by julien-louis** [comment]
Ready for review.

**Comment by pierrehenri-dauvergne** [comment]
@julien-louis :
- We can't open acquisitions in OHIF viewer anymore, the button is enabled but a click on it doesn't do anything (+ maybe change the subtitle to "View DICOM"):
image

- I feel like the research option is not visible enough, could we add a filter option at the top that would filter out every subject/exam/acquisition/dataset that do not have the searched input, something like this?
image

- If I check a couple of checkbox in a study, then open solr, then open that study from solr, I get a ExpressionChangedAfterItHasBeenCheckedError in console
image

- Whenever I open one study, go back to study list, then open another study (study can be opened from examination list or anywhere I think) I have an error: TypeError: this.globalClickSubscription is undefined

- I made some measure in OHIF viewer, that create new dataset in the acquisition. The name of the acquisition node is concatenated with all datasets (here, "abcdef", "abc", "a", "aa", etc. are all datasets of modality type "measurement"):
image

**Comment by pierrehenri-dauvergne** [comment]
- When selecting 3 acquisition from the same examination and clicking "View DICOM", the url looks like this:

https://viewer/viewer?StudyInstanceUIDs=1.4.9.12.34.1.8527.56,1.4.9.12.34.1.8527.56,1.4.9.12.34.1.8527.56&SeriesInstanceUIDs=1.4.9.12.34.1.8527.538,1.4.9.12.34.1.8527.517,1.4.9.12.34.1.8527.516
There should be only one StudyInstanceUID instead of 3 times "1.4.9.12.34.1.8527.56" (an error is shown in the viewer but shouldn't, it's still working)


- We shouldn't be able to click "View DICOM" when multiple acquisitions are selected across multiple examination. This is because the viewer doesn't know which SeriesInstanceUIDs belong to which StudyInstanceUIDs.
OK : multiple examinations selected
OK : multiple acquisitions from the same examination
KO : multiple acquisitions from multiple examinations


- I don't know if it is on purpose but the subject search includes the "HEALTHY VOLUNTEER":
image


- This error is still thrown:
If I check a couple of checkbox in a study, then open solr, then open that study from solr, I get a ExpressionChangedAfterItHasBeenCheckedError in console
image

**Comment by julien-louis** [comment]
I propose that if you select multiple acq from multiple exams it behaves just like you selected those exams.

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne for me it's ok

**Review by pierrehenri-dauvergne — APPROVED** [review]

**Pull request merged**
