### PR TITLE
Shanoir-issue#1127 Send user mail when added to study

### LINKED ISSUE #1127: Email sent when adding user to a study
Hi, 
Would it be possible to automatically send an email to a user when he.she is granted access to a study ? 
Other than that we have to send them an email manually. 
I thought this was already implemented but it seems not, 
Cheers,
Elise

### PR DESCRIPTION
**Pull request by jcomedouteau**
A mail is now sent:
- To study administrator
- To every added user
When updating a study - adding a new user

Closes #1127

### CODE REVIEW

**Review by michaelkain — APPROVED** [review]

**Comment by michaelkain** [comment]
Hi Jean-Come, nicely done, thank you! I will merge the PR and test it on qualif because of the mails. Thx and cheers, Michael

**Comment by michaelkain** [comment]
- Tested on shanoir-qualif.irisa.fr, 2021-12-15
- logged in as admin role
- 1. Test: new user added to study, study that has a study responsible with "Receive Member Mail"
	- OK, could add new member to study
	- now verify emails sent
		- OK, email found for study responsible
		- ?ERROR? I found 2 emails sent to the study responsible with the same content?
			- -rw------- 1 sink sink 1685 Dec 15 07:04 1639548254.M4938108P28Q3.qualif-smtpsink
			- -rw------- 1 sink sink 1685 Dec 15 07:04 1639548254.M4939179P28Q4.qualif-smtpsink
			- -rw------- 1 sink sink 1252 Dec 15 07:04 1639548254.M5101099P28Q6.qualif-smtpsink
		- OK, email found for new study member/user (study_user)
- 2. Test: new user added to study, study that has NO study responsible with "Receive Member Mail"
	- OK, could add new member to study
	- now verify email sent
		- OK, 1 email found
		- OK, email found for new study member/user (study_user)
- Summary:
	- in general it works! GREAT!
	- It is strange, that the study responsible with the flag "Receive Member Mail" seems to receive
	  2 mails
		- Could you please have a look on that? we should avoid spaming our study responsibles please.

**Comment by jcomedouteau** [comment]
Hi Michael,
I did the same test as you, and had the same result in smtpsink folder -> The mail to the admin was sent twice.
However, looking at the logs, the mail was only sent once.

I think we'll have to try in production to see if the mail is actually sent twice (as seen in smtpsink) or once (as seen in the logs).
I'll try it tomorrow morning !
Jean-Côme

**Comment by jcomedouteau** [comment]
@michaelkain 
I added you to my local study on prod, and received the mail only once.
Did you received it well ?

**Pull request merged**
