### PR TITLE
Clinical_score migration => back + front, + py sql migration scripts

### PR DESCRIPTION
**Pull request by jcomedouteau**
Clinical score migration.
/!\ SQL database migration changed /!\

### CODE REVIEW

**Comment by jcomedouteau** [comment]
I'm on the conflicts

**Comment by jcomedouteau** [comment]
Can be merged

**Comment by michaelkain** [comment]
Hi Jean-Come, sorry, but there is a merge conflict.

**Comment by jcomedouteau** [comment]
Must be with extra-data ! I'm on it :)

**Comment by jcomedouteau** [comment]
Launching the tests locally, then it should be OK (conflict was really simple)

**Comment by jcomedouteau** [comment]
Tests are OK

**Comment by michaelkain** [comment]
perfect, thx

**Comment by michaelkain** [comment]
Hi Jean-Come, I copied your db-migration commit into the migration scripts /docker-compose/migration_scripts/Neurinfo/4_datasets_migration.py and have some errors, they do not seem to match with the code. Could you please have a look on this and commit them? Thank you!

**Comment by jcomedouteau** [comment]
Do @Nunien or @yyao1231 have a neurinfo database so I can test the scripts ? thank's :)

**Comment by yyao1231** [comment]
@jcomedouteau Michael shared it with us on: https://partage.inria.fr/share/page/site/ng-prod/documentlibrary, but only datasets I think: datasets_dump_2020_05_06.sql.gz

**Comment by jcomedouteau** [comment]
@yyao1231 I'm not part of this site on alfresco, can you add me ? (or directly share with me the file? :) )
Only datasets is fine for me

**Comment by yyao1231** [comment]
@jcomedouteau I couldn't add you to share the doc (since I'm not the owner?) I shared it with you with fileSender finally: https://filesender.renater.fr/?s=download&token=62468d49-def6-446d-a175-a40e30303c52

**Comment by jcomedouteau** [comment]
Thanks a lot !

**Comment by michaelkain** [comment]
Hi Jean-Come, when I run mvn install now I have the following Exception:
testAddTask(org.shanoir.ng.tasks.ShanoirEventServiceTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: java.lang.ClassCastException: org.hibernate.mapping.Column cannot be cast to org.hibernate.mapping.Selectable

**Comment by michaelkain** [comment]
sorry, again my fault, a mvn clean solved it

**Comment by michaelkain** [comment]
Hi Jean-Come, there remain still some bugs in the migration script for datasets. I have started to correct them and will try to finish them. Cheers, Michael

**Comment by jcomedouteau** [comment]
Thanks a lot, it was quite complicated to develop as I couldn't test them /:

**Comment by michaelkain** [comment]
Hi Jean-Come, I have corrected the script, it is running now. There is a bug in the tree display for my test examination. Could we have a look on the together, I show you what I figured out and you tell me what is wrong.

**Comment by michaelkain** [comment]
It works great. I tested with 3 exams and they are correctly displayed. As soon as I added my commit for the mig scripts, I will accept the PR.

**Pull request merged**
