### PR TITLE
#1575 - storescu error -> use rest for dicom storage / retrieve

### PR DESCRIPTION
**Pull request by jcomedouteau**
+ Update AET (not AS_RECEIVED)
+ Better log errors, (202 = not an error)

### CODE REVIEW

**Comment by jcomedouteau** [comment]
After tests on qualif: We seem to have a probelm because of AS_RECEIVED -> application.yml changes not taken into account in qualification. This should be changed

**Comment by jcomedouteau** [comment]
Hi Michael,
Yes I completely failed my naming, it should have been upload, not download !
I tested locally for the comparison, I still need to do it on qualif.

**Comment by michaelkain** [comment]
Hi Jean-Come (@jcomedouteau), would you like to integrate this PR into the release? With kind regards, Michael

**Comment by jcomedouteau** [comment]
Hi Michael,
No I don't think so, the change to use REST instead of storeSCU seems too big and I could not test it fully yet.
Jean-Côme

**Comment by michaelkain** [comment]
I was thinking the same, thank you!

**Comment by jcomedouteau** [comment]
Concerning statistics on qualif:
sample-without-dicomdir (25mb)

REST: 28.346ms
STORESCU: 41.670ms 

sample1 (200mb)

REST: 118.954 ms
STORESCU: 20.3459ms 

Archive_MD_ERROR (512)

REST:  94.415 ms
STORESCU: 79.078ms


Seems to be generally better for rest, (not for the last ?)
Locally, it was quite the same if I remember well. Hard to tell.

**Comment by jcomedouteau** [comment]
REST
Import of 5 DICOM images into the PACS required 1147 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014185887945538699.0.0.0(localizer)
Import of 25 DICOM images into the PACS required 2325 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014204417332238734.0.0.0(loca_t2_tse_SAG)
Import of 160 DICOM images into the PACS required 8498 millis for serie: 1.3.12.2.1107.5.2.36.40296.200908101426032570039262.0.0.0(MPRAGE_iso)
Import of 160 DICOM images into the PACS required 5938 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014330119796340062.0.0.0(t2_flair_3d_iso_PRESAT)
Import of 45 DICOM images into the PACS required 1662 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014335998582440607.0.0.0(gre_field_mapping)
Import of 90 DICOM images into the PACS required 4311 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014385889507340911.0.0.0(dp t2_tse_tra_p2)
Import of 45 DICOM images into the PACS required 2517 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014393331700741336.0.0.0(t1_fl2d_tra_3mm)
Import of 44 DICOM images into the PACS required 2833 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014420035152441521.0.0.0(t1_fl2d_tra_3mm mtc)
Import of 44 DICOM images into the PACS required 1429 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014455065569441803.0.0.0(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 1929 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014460985909242040.0.0.0(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 2178 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014455065569441803.0.0.1(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 1972 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014460985909242040.0.0.1(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 1663 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014481513440142597.0.0.0(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 1958 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014484389539742840.0.0.0(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 1510 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014481513440142597.0.0.1(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 1551 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014484389539742840.0.0.1(T1 VIBE3D30° relaxo)
Import of 308 DICOM images into the PACS required 17091 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014555775881443384.0.0.0(T2 SE_MC TRA 7 echos)
Import of 308 DICOM images into the PACS required 12345 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014564932633845467.0.0.0(T2 SE_MC TRA 7 echos)
Import of 20 DICOM images into the PACS required 661 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014583383679646095.0.0.0(loca_t2_tse_AXIAL)
Import of 220 DICOM images into the PACS required 9050 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014584044568446185.0.0.0(T2STAR GRE3D TRA)
Import of 220 DICOM images into the PACS required 7763 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015023755689247501.0.0.0(T2STAR GRE3D TRA)
Import of 44 DICOM images into the PACS required 1896 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015041379656447784.0.0.0(t1_se_tra_concat_2)
Import of 62 DICOM images into the PACS required 4714 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872293547957.0.0.0(ep2d_diff_mddw_30_2EX)
Import of 55 DICOM images into the PACS required 1908 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872295447958.0.0.0(ep2d_diff_mddw_30_2EX_ADC)
Import of 55 DICOM images into the PACS required 2979 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872295747959.0.0.0(ep2d_diff_mddw_30_2EX_TRACEW)
Import of 55 DICOM images into the PACS required 2443 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872296347961.0.0.0(ep2d_diff_mddw_30_2EX_FA)
Import of 55 DICOM images into the PACS required 2315 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872296647962.0.0.0(ep2d_diff_mddw_30_2EX_ColFA)
Import of 44 DICOM images into the PACS required 1476 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015372511771667466.0.0.0(t1_se_tra_concat_2_gado)
Import of 160 DICOM images into the PACS required 4594 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015440531166067746.0.0.0(MPRAGE_iso_gado) t1_fl2d_tra_3mm)
 
Import of 1 DICOM images into the PACS required 520 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010360809945(Survey)
Import of 1 DICOM images into the PACS required 7240 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010420463968(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 5107 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010480268578(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 9534 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010531344188(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 3646 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010572901646(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 795 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011022994104(T1_3D)
Import of 1 DICOM images into the PACS required 331 millis for serie: 1.3.46.670589.11.38235.5.0.16964.2019122011070457000(VT1_3D)
Import of 1 DICOM images into the PACS required 36 millis for serie: 1.3.46.670589.11.38235.5.0.8768.2019122011070729000(VT1_3D)
Import of 1 DICOM images into the PACS required 572 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011072135326(CS FGATIR 0.9 ax)
Import of 1 DICOM images into the PACS required 266 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011105741327(EPI_BSP_AllBrain)
Import of 1 DICOM images into the PACS required 13356 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011122631540(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 5807 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011175931922(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 4355 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011225685244(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 3838 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011275825566(EPI_BSP_1.5_MB2)
 .s.n.d.c.DatasetAcquisitionApiController : Creation of dataset acquisition required 94415 millis.

**Comment by jcomedouteau** [comment]
STORESCU
Import of 5 DICOM images into the PACS required 4873 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014185887945538699.0.0.0(localizer)
Import of 25 DICOM images into the PACS required 3880 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014204417332238734.0.0.0(loca_t2_tse_SAG)
Import of 160 DICOM images into the PACS required 11351 millis for serie: 1.3.12.2.1107.5.2.36.40296.200908101426032570039262.0.0.0(MPRAGE_iso)
Import of 160 DICOM images into the PACS required 8210 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014330119796340062.0.0.0(t2_flair_3d_iso_PRESAT)
Import of 45 DICOM images into the PACS required 6177 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014335998582440607.0.0.0(gre_field_mapping)
Import of 90 DICOM images into the PACS required 6334 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014385889507340911.0.0.0(dp t2_tse_tra_p2)
Import of 45 DICOM images into the PACS required 2429 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014393331700741336.0.0.0(t1_fl2d_tra_3mm)
Import of 44 DICOM images into the PACS required 2346 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014420035152441521.0.0.0(t1_fl2d_tra_3mm mtc)
Import of 44 DICOM images into the PACS required 2428 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014455065569441803.0.0.0(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 2717 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014460985909242040.0.0.0(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 3773 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014455065569441803.0.0.1(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 8152 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014460985909242040.0.0.1(T1 VIBE3D 5° relaxo)
Import of 44 DICOM images into the PACS required 2275 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014481513440142597.0.0.0(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 2047 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014484389539742840.0.0.0(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 2182 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014481513440142597.0.0.1(T1 VIBE3D30° relaxo)
Import of 44 DICOM images into the PACS required 2272 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014484389539742840.0.0.1(T1 VIBE3D30° relaxo)
Import of 308 DICOM images into the PACS required 17813 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014555775881443384.0.0.0(T2 SE_MC TRA 7 echos)
Import of 308 DICOM images into the PACS required 21302 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014564932633845467.0.0.0(T2 SE_MC TRA 7 echos)
Import of 20 DICOM images into the PACS required 1883 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014583383679646095.0.0.0(loca_t2_tse_AXIAL)
Import of 220 DICOM images into the PACS required 11842 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081014584044568446185.0.0.0(T2STAR GRE3D TRA)
Import of 220 DICOM images into the PACS required 12752 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015023755689247501.0.0.0(T2STAR GRE3D TRA)
Import of 44 DICOM images into the PACS required 2192 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015041379656447784.0.0.0(t1_se_tra_concat_2)
Import of 62 DICOM images into the PACS required 7618 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872293547957.0.0.0(ep2d_diff_mddw_30_2EX)
Import of 55 DICOM images into the PACS required 2702 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872295447958.0.0.0(ep2d_diff_mddw_30_2EX_ADC)
Import of 55 DICOM images into the PACS required 2192 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872295747959.0.0.0(ep2d_diff_mddw_30_2EX_TRACEW)
Import of 55 DICOM images into the PACS required 2088 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872296347961.0.0.0(ep2d_diff_mddw_30_2EX_FA)
Import of 55 DICOM images into the PACS required 3145 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015063872296647962.0.0.0(ep2d_diff_mddw_30_2EX_ColFA)
Import of 44 DICOM images into the PACS required 3028 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015372511771667466.0.0.0(t1_se_tra_concat_2_gado)
Import of 160 DICOM images into the PACS required 5229 millis for serie: 1.3.12.2.1107.5.2.36.40296.2009081015440531166067746.0.0.0(MPRAGE_iso_gado) t1_fl2d_tra_3mm)

Import of 1 DICOM images into the PACS required 2195 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010360809945(Survey)
Import of 1 DICOM images into the PACS required 4269 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010420463968(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 4790 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010480268578(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 7383 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010531344188(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 4168 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122010572901646(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 1416 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011022994104(T1_3D)
Import of 1 DICOM images into the PACS required 1225 millis for serie: 1.3.46.670589.11.38235.5.0.16964.2019122011070457000(VT1_3D)
Import of 1 DICOM images into the PACS required 778 millis for serie: 1.3.46.670589.11.38235.5.0.8768.2019122011070729000(VT1_3D)
Import of 1 DICOM images into the PACS required 1532 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011072135326(CS FGATIR 0.9 ax)
Import of 1 DICOM images into the PACS required 1145 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011105741327(EPI_BSP_AllBrain)
Import of 1 DICOM images into the PACS required 3897 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011122631540(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 4217 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011175931922(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 7969 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011225685244(EPI_BSP_1.5_MB2)
Import of 1 DICOM images into the PACS required 6906 millis for serie: 1.3.46.670589.11.38235.5.0.8728.2019122011275825566(EPI_BSP_1.5_MB2)
 .s.n.d.c.DatasetAcquisitionApiController : Creation of dataset acquisition required 79078 millis.

**Comment by michaelkain** [comment]
Dear @jcomedouteau, thank you for your stats! They look good, so we should do the change. Could you please do the rename to upload? Did you have answer from dcm4chee? With kind regards, Michael

**Comment by michaelkain** [comment]
wait for release browser download
verify, how it impacts download url in dataset_file

**Review by michaelkain — APPROVED** [review]
Hi Jean-Come, thank you!

**Pull request merged**
