### PR TITLE
dowload all exam at once

### PR DESCRIPTION
**Pull request by Nunien**

### CODE REVIEW

**Comment by jcomedouteau** [comment]
When downloading from study-tree, there maybe should be a way to know  the download started (close the "download" menu and  make the to right gear roll ?).
If it's too complicated, the PR is good for me.

**Review by jcomedouteau — APPROVED** [review]

**Comment by yyao1231** [comment]
I merged the front end but the maven build failed. Any ideas?

**Comment by jcomedouteau** [comment]
Maybe linked to angular 10 switch, maybe if you just restart the build it'll work ?
I'm trying to check why the maven build fails, but it takes long. Can you launch the tests locally ?

**Comment by yyao1231** [comment]
Ok I'll check the merge locally!

**Comment by yyao1231** [comment]
C'est angular 10. Faut les merger à la main. Je m'en occupe.

**Pull request merged**
