### PR TITLE
Angular 17 to 19

### PR DESCRIPTION
**Pull request by julien-louis**
devs may need to update node  and/or npm 

https://github.com/fli-iam/shanoir-ng/issues/2387

### CODE REVIEW

**Comment by pierrehenri-dauvergne** [comment]
I have this error when deploying front-dev:
An unhandled exception occurred: Cannot find module @rollup/rollup-linux-x64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

I tried most of the proposed solution in the thread but none worked. It's opened for 2 years and it's still an issue. I'm not quite sure what to do.

**Comment by julien-louis** [comment]
Pierre Henry, 

Je crois que tu dois ajouter la dependence version windows à la suite de celle-ci. 

Julien

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne  I upgraded to angular 19 and the annoying dependencies are no longer needed

**Comment by michaelkain** [comment]
Hi! to merge before test session?

**Review by pierrehenri-dauvergne — APPROVED** [review]
To make it work, i had to use "FROM node:lts-alpine as front-dev" in Dockerfile, it uses node v23.3.0

**Pull request merged**
