### PR TITLE
upgrade to dcm4chee 5.27.0

### PR DESCRIPTION
**Pull request by a-ba**
Note that the postgresql upgrade is not automatic (need to make a full dump and import of the base). In the dev environment you can just destroy the relevant volumes.

### CODE REVIEW

**Comment by michaelkain** [comment]
Dear Anthony,
thx for your PR!!! I am just wondering if you had a look on the below link:
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql

There is a docker-compose.yml as template example given, e.g. you can find on the master and on older version some JAVA_OPTS, that are set and used, that might be interesting for us to have a stable running container maybe. It would be great to take over all adaptations necessary from the "vendor". When I integrated it into docker-compose.yml, I used the same template, in case we have an example. Let me know, when you want me to do it. Looking forward to know if the new version solves our problems on qualif.

With kind regards,
Michael

**Comment by michaelkain** [comment]
Dear Anthony, great, sorry, I did not see your comment in the docker-compose.yml.

For the JAVA_OPTS the values
-Xms64m -Xmx512m **-XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m**
do consider the memory usage of the application. I would say especially the MaxMetaspaceSize
forces the garbage collector to not allocate unlimited space, but clean up earlier. What could be
useful, especially in prod?

The below opt might have their sense too, e.g. to optimise IPv4 request handling, maybe.
-Djava.net.preferIPv4Stack=true

**Comment by a-ba** [comment]
> For the JAVA_OPTS the values
> -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m
> do consider the memory usage of the application. I would say especially the MaxMetaspaceSize
> forces the garbage collector to not allocate unlimited space, but clean up earlier. What could be
> useful, especially in prod?
> 
> The below opt might have their sense too, e.g. to optimise IPv4 request handling, maybe.
> -Djava.net.preferIPv4Stack=true


The JAVA_OPTS are already set by the entrypoint:
```
# docker top qualif-dcm4chee-arc
UID                 PID                 PPID                C                   STIME
TTY                 TIME                CMD
dcm4che+            2186862             2186844             0                   09:38
?                   00:00:00            /bin/sh /opt/wildfly/bin/standalone.sh -b 0.0.0.0
-bmanagement 0.0.0.0 -c dcm4chee-arc.xml -Djboss.management.http.port=9990
-Djboss.management.https.port=9993 -Djboss.http.port=8080 -Djboss.https.port=8443
-Djboss.redirect.https.port=8443
dcm4che+            2187435             2186862             0                   09:38
?                   00:03:50            /opt/java/openjdk/bin/java -D[Standalone] -server -Xms64m
-Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
-Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
--add-exports=java.desktop/sun.awt=ALL-UNNAMED
--add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.util.concurrent=ALL-UNNAMED
--add-opens=java.management/javax.management=ALL-UNNAMED
--add-opens=java.naming/javax.naming=ALL-UNNAMED
-Dorg.jboss.boot.log.file=/opt/wildfly/standalone/log/server.log
-Dlogging.configuration=file:/opt/wildfly/standalone/configuration/logging.properties -jar
/opt/wildfly/jboss-modules.jar -mp /opt/wildfly/modules org.jboss.as.standalone
-Djboss.home.dir=/opt/wildfly -Djboss.server.base.dir=/opt/wildfly/standalone -b 0.0.0.0
-bmanagement 0.0.0.0 -c dcm4chee-arc.xml -Djboss.management.http.port=9990
-Djboss.management.https.port=9993 -Djboss.http.port=8080 -Djboss.https.port=8443
-Djboss.redirect.https.port=8443
```

Are you suggesting to use different values ?

**Comment by michaelkain** [comment]
Dear Anthony, PERFECT! If it is set by the entrypoint totally fine for me. Thank you for your answer and with kind regards, Michael

**Review by michaelkain — APPROVED** [review]

**Pull request merged**
