### PR TITLE
Shanoir-issue#799 shanoir-issue#746 bruker/EEG import preview + select

### PR DESCRIPTION
**Pull request by jcomedouteau**
- Allow bruker preview
- Select all in select-series for bruker & EEG

### CODE REVIEW

**Review by michaelkain — APPROVED** [review]
Hi Jean-Come, perfect! I approve your PR after my code review and will now test it on my machine. With kind regards, Michael

**Comment by michaelkain** [comment]
Hi Jean-Come, with my local tests, the preview remains the same for all series, after one preview is displayed. Is that normal? With kind regards, Michael

Bildschirmfoto 2021-02-18 um 15 43 24

**Comment by jcomedouteau** [comment]
Probably not ! I'll have a look at it :)

**Comment by jcomedouteau** [comment]
Papaya was not correctly re-initialized when clicking directly on another eye => I corrected it ! Well seen :)

**Comment by michaelkain** [comment]
Hi Jean-Come, thank you for this fix. Now the preview works for all series and I can switch between them. I will merge your PR. Cheers, Michael

**Pull request merged**
