### PR TITLE
fix with LAZY and Transactional on controlers

### PR DESCRIPTION
**Pull request by julien-louis**

### CODE REVIEW

**Comment by pierrehenri-dauvergne** [comment]
This PR is a fix for https://github.com/fli-iam/shanoir-ng/issues/2520 right ?

**Comment by pierrehenri-dauvergne** [comment]
Hello @julien-louis 
Tested on qualif:
Create a study > delete study : OK
Create a study > import in a new subject > delete study : Warning, another entity is linked
Create a study > import in a new subject > delete exam of that import > delete study : Warning, another entity is linked
Create a study > import in new subject > delete subject : issue ongoing in another PR
Create a study > Create a new subject and add it to study > delete study : OK

When we delete a study, it should remove the subject from that study and also delete all data that is in that study, right ?

**Comment by julien-louis** [comment]
@pierrehenri-dauvergne  Yes it fixes https://github.com/fli-iam/shanoir-ng/issues/2511 and also https://github.com/fli-iam/shanoir-ng/issues/2520

Is there any regression with that code ? If not I think we could merge it.

**Review by pierrehenri-dauvergne — APPROVED** [review]
I didn't see any regression while testing. Merging this so we can move forward on other issues

**Pull request merged**
