### PR TITLE
Nifti pr merge

### PR DESCRIPTION
**Pull request by julien-louis**
replacement of https://github.com/fli-iam/shanoir-ng/pull/1849 

Here is the diff between the merge from develop + my modifications and your pr : https://github.com/jcomedouteau/shanoir-ng/pull/111/files

### CODE REVIEW

**Comment by julien-louis** [comment]
I made the class DownloadInputIds to force the good use of the multiple possible arguments in download (datasetIds, studyId, ...)

**Comment by jcomedouteau** [comment]
I'm testing it !

**Comment by jcomedouteau** [comment]
@julien-louis I think there is a conflict :'(

**Comment by jcomedouteau** [comment]
Closing this one as we have another one ready.

**Pull request closed without merging**
