### PR TITLE
Fix for GitHub issues: #540 (Pacs import)+#561: import data issue

### PR DESCRIPTION
**Pull request by michaelkain**
Prod: import from pacs: use exam date to sort request answer after Pacs query #540
- PatientRootQuery now considers dicom study date and study description as additional criteria
- Dicom study level ordered by study date (-> exam in Shanoir) old to newest
- Dicom tree: displays now the date of the Dicom study (-> exam in Shanoir)
- Wrong date display of Dicom study fixed

### CODE REVIEW

**Comment by michaelkain** [comment]
@Nunien Hi Julien, could you just do a code review, to see if I have not "damaged" something in the front. My tests all worked well. For the final Pacs acceptance test, I will ask Elise to test on qualif herself.

**Comment by michaelkain** [comment]
Hi Julien, could you review this please, that we can bring it to qualif asap? Thank you, Michael

**Comment by michaelkain** [comment]
@Nunien Hi, as I did not have answer from you, and as this fixes are quite required I merged them today. With kind regards, Michael

**Comment by ebannier2018** [comment]
Hi, I tried some PACS imports today on qualif. The request Patient Name : PHANTOM QUALITE 20200925 gives me more than the one expected answer. The patient name "PHANTOM QUALITE 20200925" should be considered as a whole and I should only get one examination as an answer. Trying to filter with study date I could get the one examination only which was not working on prod and this is good, but I expect only one answer on the patient name request anyway, since the patient name is unique. It should NOT return the result of PHANTOM or QUALITE or 20200925 as seems to be the case. No wildcard should be possible there either as we agreed. 

Capture d’écran 2020-10-26 à 10 08 23

Also : 
- the multiple examinations are ordered from oldest to newest and we expect the contrary (newest first). 
- they should not show as examinations from the same subject, since the patient names are different. 

Last, I do not agree with the following description : 
Please fill at least one of the five fields below to query the PACS. Blank is not allowed.
If Patient Name, Patient ID or Patient Birth Date is filled, a PatientRoot query is send to the PACS.
You can fill Study Description and Study Date in combination with the three patient values above to affine your search.
If only Study Description or/and Study Date is filled a StudyRoot query is send to the PACS.

To  me Patient Name is mandatory and should be considered as a whole. Patient ID and Patient Birth I do not see the use. Do some users do? 
Study Date can be used to affine the search indeed. Study Description also but not sure is it useful. 
So StudyRoot query should be sent is only Study Description or Study Date are filled since Patient Name is mandatory. 

We can discuss this over the phone if this is not clear. 

Cheers, 
Elise

**Comment by ebannier2018** [comment]
Any news on this to consider the patient name as a whole (e.g. "PHANTOM QUALITE" is "PHANTOM"and "QUALITE" not "PHANTOM" or "QUALITE") ?

**Comment by ebannier2018** [comment]
Short reminder on this issue, if you could take a look

**Pull request merged**
