### PR TITLE
Shanoir extra data

### PR DESCRIPTION
**Pull request by jcomedouteau**
Add extra data files when creating examination
Add possibility to download them
When examination is deleted, files are deleted too

### CODE REVIEW

**Comment by michaelkain** [comment]
maybe using Java system properties to get access to a temp directory on any OS?

**Comment by jcomedouteau** [comment]
It works for me, but it's true that it supposes to work on linux and to have a /tmp folder which is not so smart !
I should have used temporary folder:
https://howtodoinjava.com/junit/junit-creating-temporary-filefolder-using-temporaryfolder-rule/

I think I made the same mistake for study protocol file

**Comment by michaelkain** [comment]
maybe you forgot your application.yml to commit? I am just guessing

**Comment by michaelkain** [comment]
no problem, that is the good thing of pull requests :-)

**Comment by michaelkain** [comment]
ah, nice with the TemporaryFolder, I guess internally they use Java System props java.io.tmpdir or something like this

**Comment by jcomedouteau** [comment]
Yes probably.
I also have to force the value of where is located the data because it would use /var/... otherwise which is also a specific linux path.
I'm on it

**Comment by jcomedouteau** [comment]
@michaelkain I pushed a new commit, can you tell me if it works for you ?
Thanks

**Comment by michaelkain** [comment]
Hi, better, but not working yet, results :
Failed tests: 
  ExaminationApiControllerTest.testDownloadExtraData:240 null

**Comment by jcomedouteau** [comment]
Can you give me the error displayed the line before it fails ?

**Comment by michaelkain** [comment]
sorry, I was not aware, that there were more infos above, I only saw the end result.
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.http.InvalidMediaTypeException: Invalid mime type "null": 'mimeType' must not be empty

**Comment by jcomedouteau** [comment]
Can you try again ? Thanks

**Comment by jcomedouteau** [comment]
I'm on the conflicts..

**Comment by jcomedouteau** [comment]
Can be merged

**Comment by michaelkain** [comment]
Hi Jean-Come, mvn install worked and docker-compose runs up (when I set manually before to lamyj/dicomifier; what is strange as I commited this change to develop). I can create new examinations using the import and I gave myself admin rights on one study (I am already admin too), BUT I can not edit an examination to test the feature. Is this one of your bugs already identified? should I merge?

**Comment by michaelkain** [comment]
One second, I will verify one point, maybe I mixed up with the pull request numbers, sorry

**Comment by michaelkain** [comment]
sorry, yes, I pulled the wrong number, forget what I wrote

**Comment by michaelkain** [comment]
by the way, now on the correct pull request, even after having changed to lamyj/dicomifier, I have this error:
preclinical-bruker2dicom    | python3: can't open file '/root/run.py': [Errno 2] No such file or directory
preclinical-bruker2dicom exited with code 2

**Comment by michaelkain** [comment]
Hi Jean-Come, same results:
Testing of Extra Data
- Manage Preclinical examinations: list throws an error
- The button Attach Extra Data is always grey, even when
using https://shanoir-ng-nginx/shanoir-ng/examination/edit/1
- I created a new exam with the web import and button grey
- I checked: the rights in study_user_study_user_rights are correct
in ms studies and ms datasets
- I did not find a way to attache a file

**Comment by jcomedouteau** [comment]
I'll have a look at it. I thought I tested it

**Comment by jcomedouteau** [comment]
It works for me 
image
But only during creation => I'll change this, I only though it was impossible to edit an exam :)
Manage Preclinical examinations: No pb on my side.. Maybe you have to clean your data so the database schema can be updated correctly ?

**Comment by michaelkain** [comment]
Testing of extra data, with Firefox 76.0.1 (64-Bit)
Using admin account
1.1. Edit existing examination and add extra data (1 file)
Web Import started and new exam created, as edition of existing exams not possible,
maybe because I am not member of the study of the exam
Works, I could add the file, but
Bug 1) I can not download the file "seam_reference.pdf", when I click nothing happens
BUT it worked with two other named files
1.2. Edit existing examination and remove extra data (1 file)
Bug? Edition not possible, now my ms users is running as I fixed it
Bug? I still have an error when managing preclinical exams

**Comment by jcomedouteau** [comment]
=> It's not possible to edit an examination, I thought it was a rule ?

**Pull request merged**
