### PR TITLE
Downloader resources in jar

### PR DESCRIPTION
**Pull request by arthursw**
Load the downloader config from resources in the .jar instead of loading from `/home/userName/.suShanoirVersion/`

### CODE REVIEW

**Comment by michaelkain** [comment]
Hi Arthur, sorry for being picky, but could you please make a PR dedicated to ShUp and the issue? This one contains the the downloadStats part too, what I would like to test and add separately. Thank you, Michael

**Comment by arthursw** [comment]
I'm sorry I must have messed up my develop branch. I'll fix that.

**Review by michaelkain — CHANGES_REQUESTED** [review]
Hi Arthur, sorry for this feedback, but this will still not work. The user enters a host on the command line, that should be used, and called. So you will have to use this host URL in two places:
1) for Keycloak auth, to address the correct server: host-url-by-user + "/auth" for your method
keycloakAuthentification(String host, String username, String password) == auth-server-url
2) as property for NGClient (that is what you already do, as far as I understand :-)).

**Comment by arthursw** [comment]
Ok I'll fix that!

**Comment by arthursw** [comment]
Should I prefix the host with "https://" when `port` is 433 and with "http://" when `port` is 22?

**Comment by arthursw** [comment]
I guess yes, so I'll do that for now.

**Review by michaelkain — APPROVED** [review]
Thank you, looks fine. I will merge and then test on my machine, as this will be part of ShUp v7.0.1.

**Pull request merged**
