### PR TITLE
Appning fix

### PR DESCRIPTION
**Pull request by jcomedouteau**
Fix appning litlle bugs

### CODE REVIEW

**Comment by michaelkain** [comment]
Hi Jean-Come, I started to test this fix. mvn install works and it runs up (only when I change dicomifier.ws, by the way could you share your latest image with me, that it works for me too?). I have not picked your last commit as I started this morning, but I can see no manage table, as I have an error everywhere (studies, subjects, examinations, etc. nothing is displayed). Is this a bug on my side or do you have an explanation, or is this in your last commit?

**Comment by michaelkain** [comment]
sorry, maybe it is my fault, I did a docker volume clean, but missed compose down before, I retest

**Comment by jcomedouteau** [comment]
Ok ! I'm sending you the last image (I forgot to put it on dockerhub...!)

**Comment by michaelkain** [comment]
Now, it is fine, no direct errors and all tables are displayed.

**Pull request merged**
