### PR TITLE
#1783-Solr update after import + study card

### LINKED ISSUE #1781: [SOLR] New datasets are not uploaded in SOLR
With quality card development, the method used to save acquisition equipments is not the same anymore.

We use to pass in 
datasetAcquisitionService.create(datasetAcquisition);
method, that was sending the CREATE_DATASET_ACQUSITION_EVENT event.

We are now using:
datasetAcquisitionRepository.saveAll(generatedAcquisitions);

How to correct:
- Create a method "createAll" in  DatasetAcquisitionService(Impl) that will save all acqusition and publish an event for every dataset acquisition.
- Use this method in ImporterService to create all acquisitions

### LINKED ISSUE #1783: Re-apply study cards: Solr index not updated (if dataset meta-data changed)

### PR DESCRIPTION
**Pull request by jcomedouteau**
Closes #1783 
Closes #1781

How to test:
- Import some data
-> These data are now well imported in SOLR
- (Re)Apply a study card that will change something visible in shanoir
-> The datasets are updated in solr

### CODE REVIEW

**Comment by pierrehenri-dauvergne** [comment]
Reapplying a study card isn't working. Here is the stacktrace

[stacktrace.txt](https://github.com/fli-iam/shanoir-ng/files/12080764/stacktrace.txt)

**Review by pierrehenri-dauvergne — COMMENTED** [review]
Error while reapplying a study card. Here is the stacktrace :
[stacktrace.txt](https://github.com/fli-iam/shanoir-ng/files/12080776/stacktrace.txt)

**Comment by jcomedouteau** [comment]
Hi @pierrehenri-dauvergne, thanks for the review. It should be good now!

**Comment by jcomedouteau** [comment]
I'm really sorry, but I can't reproduce your bug @pierrehenri-dauvergne.
Where do you re-apply study card from ? Can you test from solr search (seems that from study card detail, it's still broken)
Otherwise, did you reset your solr volume before testing ? (i'm quite lost I have to say)

**Comment by pierrehenri-dauvergne** [comment]
I tested again and you're right. The error I got was from the study card details (I still have that error) but it's working well from the solr "apply study card" button.

**Review by michaelkain — APPROVED** [review]
Hi, I approve here by code review.
I will merge it into my PR Spring Boot 3 and go a little further.
I am wondering why we pass by RabbitMQ within the same microservice to index datasets.
The DatasetAcquisitionRepo should be compelety removed from ImporterService and put into the DsAcService. Same: delete SolrService from ImporterService (unused today).

**Pull request merged**
