### PR TITLE
Sonar integration

### PR DESCRIPTION
**Pull request by jcomedouteau**
@Nunien Before merging this pull request:

0. IMPORTANT: change shanoir-ng default branch on github to develop
1. Go on https://sonarcloud.io/
2. Connect as fli-iam if you have the password (I hope so)
3. Analyze this fli-iam/shanoir-ng repo (+ on top right, "analyze new project" then select shanoir-ng)
4. Select 'github action' analyze type
5. Get the "secret" token that you have to reference in github (parameters/secret)
6. Merge this pull request
7. Reset default branch to master
8. Check that the build launched and that all is OK

Now every nest PR will launch a sonar cloud build.

### CODE REVIEW

**Comment by Nunien** [comment]
@jcomedouteau Do you know what consequences exactly can result from setting the develop branch as default. Actually I wanted to do that earlier but I was discouraged by a warning message that says it can have consequences but I don't know exactly what.

**Comment by jcomedouteau** [comment]
We can discuss this this afternoon and do it together if you want :)

**Comment by Nunien** [comment]
c'est bon j'ai changé

**Review by Nunien — APPROVED** [review]

**Comment by Nunien** [comment]
@jcomedouteau I discussed this with @michaelkain and the questions are : 
* why does it have to run on the sonar cloud server ?
* is there a solution for it to run directly on the build, either on GitHub or on the computer that builds shanoir ?

**Comment by jcomedouteau** [comment]
The other solution if we don't use sonarCloud is to install a local sonar server that runs the analysis. Currently the maven build is directly integrated to github if I'm not wrong ?
SonarCloud is specifically made for open source projects, that's the interesting point, but we can discuss this afternoon !

**Comment by jcomedouteau** [comment]
I'm closing this as we're not ready yet to integrate sonarcloud :)

**Pull request closed without merging**
