### PR TITLE
Pet import

### PR DESCRIPTION
**Pull request by yyao1231**
first version of pet import.
as discussed yesterday with MK, this version contains only pet modality dicom zip import. we consider that all pet required metadata is presented by default. the dicom zip is imported without studycard, like CT implentation.
other features described on the wiki should be implemented in the next version.

ps I could not test the ms datasets part yet. still blocked by the issue #718

### CODE REVIEW

**Comment by michaelkain** [comment]
Hi Yao, I do not understand why you could not test. The issue you mention is about the debug mode, okay, what helps to develop if necessary, but why you can not test, I do not know. With kind regards, Michael

**Comment by yyao1231** [comment]
Hi @michaelkain I mean the debug mode will help. The issue is resolved this morning by the way, please see my commits above.
The problem is that the pet import could not end normally. There is one error in the event table. But nothing in the logs. 
Jean-côme told me about the shared /tmp folder pb, I will see. Just be aware that the pr is not finished yet since the test is not ok.

**Comment by yyao1231** [comment]
I tested the mr, pet and ct import, without any ms en debug mode. same error in the event list for all modalities (mr pet and ct).. no error found in the logs.. Someone has any ideas?

**Comment by michaelkain** [comment]
Hi Yao, I am happy that we could help you in the weekly meeting yesterday to progress. Now that you deactivated your debug mode in ms datasets, it helped you to progress, so no relation with the issue you mentioned above. Have you done a full clean of your environment? Have you tested without the PR Angular 10?, that maybe could be related to this, but I am just guessing. If, we will see with our tests at 10h. By the way your error description above is not very precise. In any case it would be great to have this pull request running as we started the development on it 16 work days ago. Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment]
We're working on it Michael :)
The problem is the change of workpath:
image

This'll be corrected soon

**Comment by michaelkain** [comment]
Hi, thx Jean-Come for helping out. Sorry, that I have not commented it on GitHub yesterday, but when I skipped through it (unfortunately I did not take the time) I saw this change in the PR and found it quite "dangerous" too. Sorry, that I did not comment it directly. Cheers, Michael

**Comment by yyao1231** [comment]
yes it seems to work the pet import, and the mr ct also. sorry I committed the workfolder changes for debug mode! someone could test the pr now. I will continue my test and dev to prepare the futur version.

**Comment by jcomedouteau** [comment]
On my side, nifti conversion didn't went well
=> In consequences, there is no nifti (to download or fr preview)

datasets                    | 2021-01-08 10:50:07.421  WARN 1 --- [cTaskExecutor-1] .s.n.i.s.d.PetDatasetAcquisitionStrategy : No studycard given for this import
datasets                    | 2021-01-08 10:50:07.479 ERROR 1 --- [cTaskExecutor-1] s.n.i.s.d.NiftiDatasetExpressionStrategy : IOException generating nifti Dataset Expression
datasets                    | 
datasets                    | java.nio.file.NoSuchFileException: /tmp/3/5862852404255335322/SERIES/1.3.46.670589.28.2.12.4.9172.4427.2.200.0.1223906269/%5BRG-WB_CTAC_2mm%5D%20Pulmo%20PET%20Body0_1.json
datasets                    |   at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
datasets                    |   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
datasets                    |   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
datasets                    |   at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
datasets                    |   at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
datasets                    |   at java.nio.file.Files.copy(Files.java:1274)
datasets                    |   at org.shanoir.ng.importer.strategies.datasetexpression.NiftiDatasetExpressionStrategy.generateDatasetExpression(NiftiDatasetExpressionStrategy.java:86)

**Comment by yyao1231** [comment]
thanks @jcomedouteau for your test. I tested nifti download yesterday and it works fine. Which converter did you use? I'll check with the same one as you.

**Comment by jcomedouteau** [comment]
It works well with dcm2niix, but failed with dicomifier

**Comment by jcomedouteau** [comment]
I'm wondering if it's not linked to the file name but I'm not sure, and it should fail with others too..

**Comment by yyao1231** [comment]
ok tks Jean-Côme. by file name, you mean dicom file name? They are like IM-0020-0001.dcm in the zip that I shared with you. Maybe I could download dicomifier to test the conversion by command line. Otherwise, I will search if I have some other pet data with different file name structure..

**Comment by yyao1231** [comment]
oh oh dicomifier seems to work for linux/anaconda only.. My first solution is not possible for my os.. Could someone try it? to know if the conversion pb comes from dicomifier or my pet images zip?

**Comment by jcomedouteau** [comment]
I'm checking the dicomifier problem !

**Comment by jcomedouteau** [comment]
Je pense que le soucis vient définitivement du nom de fichier:
java.nio.file.NoSuchFileException: 
/tmp/3/3437983463549261749/SERIES/1.3.46.670589.28.2.12.4.9172.4427.2.200.0.1223906269/%5BRG-WB_CTAC_2mm%5D%20Pulmo%20PET%20Body0_1.nii

Alors que le fichier existant est:
[RG-WB_CTAC_2mm] Pulmo PET Body0_1.nii

Donc peut-être les crochets ?

**Review by jcomedouteau — APPROVED** [review]

**Comment by yyao1231** [comment]
J'ai noté le pb de téléchargement nifti dans un issue: #759

**Pull request merged**
