### PR TITLE
shanoir-issue#2240: rename 'acquisition equipment' to 'center equipment'

### PR DESCRIPTION
**Pull request by pierrehenri-dauvergne**
How to test:
Open the center-equipment list and check there is a new column "modality"

The searches in this list and new column are working
The "acquisition equipment" was renamed to "center equipment" in breadcrumbs and in some fields (coils, study card, imports, etc)

### CODE REVIEW

**Comment by pierrehenri-dauvergne** [comment]
Also rename "center" to "acquisition center" in the front-end only

**Review by jcomedouteau — APPROVED** [review]

**Comment by jcomedouteau** [comment]
Hello @pierrehenri-dauvergne, j'ai un petit souci sur la liste des équipements, je ne peux pas ouvrir le détail d'un équipement:
image

Je pense que c'est au niveau du routing d'angular, center-equipment ne doit pas vraiment exister.

**Review by jcomedouteau — CHANGES_REQUESTED** [review]
Voir commentaire ci-dessus

**Review by jcomedouteau — APPROVED** [review]
Works well for me.

**Review by jcomedouteau — CHANGES_REQUESTED** [review]
Change is missing in some places

**Comment by jcomedouteau** [comment]
Breadcrumbs:
image
Dataset acquisition list
image

**Review by jcomedouteau — APPROVED** [review]

**Pull request merged**
