### PR TITLE
shanoir-issue#534 Order dataset acquisition

### PR DESCRIPTION
**Pull request by jcomedouteau**
- Ordre dataset acquisition in study-tree following sorting index (corrected)

### CODE REVIEW

**Review by michaelkain — CHANGES_REQUESTED** [review]

**Comment by jcomedouteau** [comment]
The PR is now using back to order dataset acquisition (it's not really more beautiful but anyway)

**Review by Nunien — APPROVED** [review]
Not tested

**Comment by ebannier** [comment]
Tested on several studies. Now working, also for examinations imported before Sep 22nd 2020, ie before Shanoir-NG. Thanks a lot.

**Comment by ebannier** [comment]
Hi, I was looking at some data from the AVCPOSTIM study and noticed the series where not in the acquisition order : see AVCPOSTIM VS 06 YB. I had validated the correction on some recent (imported after Sep 22nd) and older studies (imported before Sep 22nd). However checking again today the series are in the acquisition order only for those imported after Sep. 22nd. Can you check on your side ?

**Comment by jcomedouteau** [comment]
@ebannier Yes we had a problem last week that made us come back on all developments since the 15th of January approx.
It'll be back on wenesday :)

Jean-Côme

**Pull request merged**
