### PR TITLE
Shanoir-issue#605 Session using BIDS + move BIDS to datasets MS

### PR DESCRIPTION
**Pull request by jcomedouteau**
- Add session if necessary only
- Move all BIDS logic to datasets

### CODE REVIEW

**Comment by Nunien** [comment]
@jcomedouteau What should I test? That the BIDS tree works properly? Does this impact BIDS import?

**Comment by jcomedouteau** [comment]
What needs to be tested:
- That BIDS is well generated / updated / deleted when creating / updating / deleting a study / exam / importing a dataset
- That the session level is set only if there is multiple examinations for a subject

**Comment by jcomedouteau** [comment]
Yes I'll do it :)

**Review by michaelkain — COMMENTED** [review]
Hi Jean-Come,
really well done.
Some more minor comments after my review:
- shanoir-ng-users/src/main/resources/application.yml
	- should normally not be part of this PR as not related to BIDS
	- normally it is good, that the dev profile initiates the db?
	- same for?
		- shanoir-ng-studies/src/main/resources/application.yml
		- shanoir-ng-datasets/src/main/resources/application.yml

Thank you and with kind regards,
Michael

**Comment by jcomedouteau** [comment]
Thanks for the feedbacks ! I'll correct for monday. It seems indeed that some files are part of another commit...

Jean-Côme

**Comment by jcomedouteau** [comment]
I corrected the scories on the different application.yml files. You can test.

Jean-Côme

**Comment by jcomedouteau** [comment]
Hi Michael,
I encounter some problems with the study cards. I think you can wait a bit before testing !
Thanks,
Jean-Côme

**Comment by jcomedouteau** [comment]
It's OK now.

**Comment by michaelkain** [comment]
Hi Jean-Come, I will start my testing. Cheers, Michael

**Comment by jcomedouteau** [comment]
Don't bother calling me if necessary, so that it's faster.

**Comment by michaelkain** [comment]
Hi Jean-Come,
I finished my local tests and unfortunately the result is missing quite some items, sorry.
Please see below:
- Testing on local machine
	- Test SC created, no rules
	- Import DICOM sample.zip
	- New subject + new exam created: MK-2022-01-21-1
	- Import successful
	- MAJOR ERROR:
		- **I can not open/use the NIfTI file, downloaded!**
		- single file download used, by click on nifti file
	- **BIDS tree verification**
		- OK 1 serie found in "undefined"
		- **ERROR, to correct:** file names finish json/gz, "." is missing
			- already written by email
		- **Minor error**: click on README: nothing happens
		- Test of download dataset_description
			- OK, download .zip and json opened
			- **Minor error**: missing: "DatasetType": "raw"
		- participants.tsv
			- OK, download .zip and .tsv opened, in Numbers
			- **ERRORS, to correct**:
				- participant_id does NOT start with sub-1
				- see spec of BIDS
					- The purpose of this RECOMMENDED file is to describe properties of participants such as age, sex, handedness. If this file exists, it MUST contain the column participant_id, which MUST consist of sub-<label> values identifying one row for each participant, followed by a list of optional columns describing participants. Each participant MUST be described by one and only one row.
				- MISSING: age + sex + both hemi-dominances, if existing
		- stud-1_DemoStudy_scans.tsv
			- Error: file names finish json/gz, "." is missing
		- sub-2_MK-2022-01-21-1_scans.tsv
			- ERROR, to correct
				- file is empty, BUT should contain one serie?
		- NIfTI and JSON files download
			- Error to correct:
				- gz.zip is wrong as the downloaded file name
- Possible extension proposal
	- Link to subject view, when clicking on the folder of the subject "sub-2-MK-2022-01-21-1"

**Comment by michaelkain** [comment]
Bildschirmfoto 2022-01-21 um 09 24 25
gz.zip, I can not use the nifti file

**Comment by jcomedouteau** [comment]
>I can not open/use the NIfTI file, downloaded!
I'm investigating on what's happening for the nifti files, it's quite weird.

> Minor error: click on README: nothing happens
I made the choice to display only .json and .tsv files. But we can imagine making an exception for the README.

> Minor error: missing: "DatasetType": "raw"
> participant_id does NOT start with sub-1
I'll update this, this is in the new version, I hadn't checked.

> MISSING: age + sex + both hemi-dominances, if existing
The problem here is that we are in dataset microservice, we don't have access unless we make a specific request to get these data. I was wondering if that was worth.

> file is empty, BUT should contain one serie?
I'll check again how I generate this file

Thanks for the feedbacks, I need to test better my PRs !

**Review by michaelkain — APPROVED** [review]

**Comment by michaelkain** [comment]
There seems to be a failed test: 2022-01-21T16:18:04.8102160Z Failed tests: 
2022-01-21T16:18:04.8102523Z   BidsServiceTest.testExportAsBids:141 null

**Pull request merged**
