### PR TITLE
shanoir-issue#1078 Import direct in solr tag

### LINKED ISSUE #1078: [TAG/SOLR] newly imported subject is not well tagged in solr

### PR DESCRIPTION
**Pull request by jcomedouteau**
Import with a new subject
Tag the subject directly from the import clinical context
Solr tags are updated

Closes #1078

### CODE REVIEW

**Comment by jcomedouteau** [comment]
I'll check this :)

**Comment by michaelkain** [comment]
Great, THX!

**Comment by jcomedouteau** [comment]
Can you retry now @Nunien ?

**Comment by michaelkain** [comment]
@Nunien Hi Julien, for the go-live could you have a look on that with priority please? Thank you, Michael

**Comment by Nunien** [comment]
@michaelkain @jcomedouteau 
It works, good job Jean-Côme.
However I reduced even more the number of calls to de database and I think it works very well. I couldn't integrate my code to this pr so I created a new one : https://github.com/fli-iam/shanoir-ng/pull/1088

**Pull request closed without merging**
