### PR TITLE
Protocol file on Study - front + back + tests

### PR DESCRIPTION
**Pull request by jcomedouteau**

### CODE REVIEW

**Comment by jcomedouteau** [comment]
I'm on the conflicts

**Comment by jcomedouteau** [comment]
can be merged

**Comment by michaelkain** [comment]
Hi Jean-Come, mvn install does finish with failures:
Failed tests: 
  StudyApiControllerTest.testDeleteProtocolFile:182 null
  StudyApiControllerTest.testDeleteProtocolFileNotLinked:234 null
  StudyApiControllerTest.testDownloadExtraData:325 null
  StudyApiControllerTest.testDownloadProtocolFile:262 null
  StudySecurityTest.testFindByIdAsUserThatCanSee:105 This should return an AccessDeniedException.

**Comment by jcomedouteau** [comment]
Arg ! Did you pull the last commit ?

**Comment by michaelkain** [comment]
MacBook-Pro-7:shanoir-ng-parent mkain$ git log
commit c4d7a32dd592fec21c6f7dd68f30ed83db6da5e1
Author: jcomedouteau <jean-come.douteau@inserm.fr>
Date:   Wed May 13 12:31:35 2020 +0200

    Correct tests

**Comment by michaelkain** [comment]
Hi Jean-Come, I hope it helps: I have sent you the mvn install output by mail :-)

**Comment by jcomedouteau** [comment]
Yep thanks !
We currently have out GIN team meeting right now, I'm on it after :)

**Comment by jcomedouteau** [comment]
I corrected the tests, I was using /tmp/ folder and not temporary folder test Rule. Should be better now.

**Comment by michaelkain** [comment]
mvn install working, I will start to test, by the way I achieved to run the Selenium tests

**Comment by michaelkain** [comment]
I created a new study and added a file. It is displayed as available, but I can not download it. In the log of ms studies I have the following error:
Caused by: java.lang.NumberFormatException: For input string: "undefined"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:211)
	at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:113)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:468)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:441)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:199)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:108)
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:64)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:47)
	at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:688)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:115)
	... 97 common frames omitted

**Comment by michaelkain** [comment]
my file name was: 20140922-MOD-FICHE_REGISTRE-VD.pdf

**Comment by michaelkain** [comment]
I think the bug is in the upload, now I can not upload anymore

**Comment by jcomedouteau** [comment]
Seems to be a front problem - sending undefined instead of the study ID

**Comment by jcomedouteau** [comment]
I'm testing it again

**Comment by michaelkain** [comment]
ah, my ms users is not running, can this be the problem?

**Comment by jcomedouteau** [comment]
Mmm seems weird

**Comment by michaelkain** [comment]
in the front I see: EventSource's response has a status 503 Service Temporarily Unavailable that is not 200. Aborting the connection.

**Comment by jcomedouteau** [comment]
And what is the http request?

**Comment by michaelkain** [comment]
what is weird too, I have quite a few in the log of ms studies:
2020-05-14 15:06:20.915 ERROR 1 --- [http-nio-9902-exec-1] o.k.a.BearerTokenRequestAuthenticator    : Failed to verify token
org.keycloak.exceptions.TokenNotActiveException: Token is not active

**Comment by michaelkain** [comment]
ah, users: https://shanoir-ng-nginx/shanoir-ng/users/users

**Comment by jcomedouteau** [comment]
Maybe if users is not running it can not check user's rights ?

**Comment by michaelkain** [comment]
how do you set the mail server, when I use localhost or SMTP_HOST it does not run up

**Comment by jcomedouteau** [comment]
I configure it manually in keycloak I think

**Comment by michaelkain** [comment]
my problem is, ms users does not run up, because of the not accessible mail server spring.mail.host=SMTP_HOST

**Comment by michaelkain** [comment]
and why is ms studies calling ms users for study edition?

**Comment by michaelkain** [comment]
does ms users run up with the default config in .env? crazy, not on my machine

**Comment by michaelkain** [comment]
java.net.UnknownHostException: SMTP_HOST. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: SMTP_HOST, 25; timeout -1;
  nested exception is:
	java.net.UnknownHostException: SMTP_HOST
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:432)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:345)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:362)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350)
	at org.shanoir.ng.email.EmailServiceImpl.notifyUserResetPassword(EmailServiceImpl.java:182)
	at org.shanoir.ng.ShanoirUsersManagement.createUsersIfNotExisting(ShanoirUsersManagement.java:189)
	at org.shanoir.ng.ShanoirUsersManagement.run(ShanoirUsersManagement.java:138)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	... 14 common frames omitted
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: SMTP_HOST, 25; timeout -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
	at javax.mail.Service.connect(Service.java:366)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:501)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:421)
	... 21 common frames omitted
Caused by: java.net.UnknownHostException: SMTP_HOST
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
	... 25 common frames omitted

**Comment by michaelkain** [comment]
Hi Jean-Come, let's continue tomorrow, I guess my missing ms users is causing problems, what seems to be the major problem.

**Comment by jcomedouteau** [comment]
Okay, I'll try to see how it works locally for me. (and if protocol files works for me)

**Comment by michaelkain** [comment]
Great, thank you!

**Comment by jcomedouteau** [comment]
I commited something I though was already done. Should work better now. I don't think it's linked to user MS.
But that's a good question anyway, I don't know how does it work without mail smtp config...

**Comment by michaelkain** [comment]
For documentation reasons
* Tests #287 study protocol file, recorded with SeleniumIDE
1.1. Create a new study and attach file directly
1.2. Verify save and access to file
works
1.3. Delete study and verify successful deletion
2.1. Open an existing study and attach file
2.2. Verify save and access to file
works
3.1. Open an existing study, with protocol file and remove it and save
3.2. Verify save and file removed
works
Bug 1: changing the protocol file of a study does not allow an update
Bug 2: isClinical is mandatory, but not checked, this makes no sense

**Pull request merged**
