### PR TITLE
Shanoir issue#1073 Access request

### PR DESCRIPTION
**Pull request by jcomedouteau**

### CODE REVIEW

**Comment by julien-louis** [comment]
Hi @jcomedouteau have you tested it on qualif ? I have an error log when I try to submit an account request : 
```
javax.validation.ConstraintViolationException: Validation failed for classes [org.shanoir.ng.accountrequest.model.AccountRequestInfo] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='must not be null', propertyPath=contact, rootBeanClass=class org.shanoir.ng.accountrequest.model.AccountRequestInfo, messageTemplate='{javax.validation.constraints.NotNull.message}'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
...
        at org.shanoir.ng.user.service.UserServiceImpl.createAccountRequest(UserServiceImpl.java:266)
```
I couldn't get any further

**Comment by jcomedouteau** [comment]
Hi Julien,
You're right, contact is not mandatory anymore on the front, but still is in the back. I never tested without contact.
I'll update this.
Jean-Côme

**Comment by jcomedouteau** [comment]
- Update members table directly when adding directly user from mail

**Comment by jcomedouteau** [comment]
Visual for homepage
image

**Comment by jcomedouteau** [comment]
When coming from invitation -> Study name from access request is not displayed correctly

**Comment by julien-louis** [comment]
2.2) Connected user requests an access on a public study
2.2.1) This access request is accepted by the study manager -> email send to user and study managers
2.2.2) This access request is refused by the study manager -> email send to user
    * After clicking "refuse", the "Request from" link on members tabs is still there

**Comment by jcomedouteau** [comment]
Invite already existing user -> can add multiple times

**Comment by jcomedouteau** [comment]
After accept -> Go to "members" (# problem ?)

**Comment by jcomedouteau** [comment]
@michaelkain @julien-louis I normally corrected the problems we encountered yesterday.

**Comment by michaelkain** [comment]
Tested successfully today, all remaining issues corrected. @jcomedouteau THANK YOU!

**Review by michaelkain — APPROVED** [review]

**Pull request merged**
