### PR TITLE
Keycloak migration to 10.0.0

### PR DESCRIPTION
**Pull request by michaelkain**

### CODE REVIEW

**Comment by michaelkain** [comment]
Hi Julien, I am stuck with a JavaScript problem with Keycloak on this PR. Starting with clean docker volumes the PR starts fine, all microservices run up, Keycloak 10.0.0 is up, accessible and running. When I open the login url: https://shanoir-ng-nginx, I have a JavaScript error within the keycloak.service.ts. I have spent 3 hours on that already, maybe you could have a look. The JS error is: Unhandled Promise rejection: Promise.prototype.then called on incompatible Object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Promise.prototype.then called on incompatible Object

**Comment by jcomedouteau** [comment]
The first time I ran the script i had:
14:04:58,460 FATAL [org.keycloak.services] (ServerService Thread Pool -- 73) java.lang.RuntimeException: Failed to connect to database
=> So keycloak doesn't start successfully.
But keycloak-database is running well. 

I launched it a second time, and it worked well.. Quite strange !

Then when deploying front, I have this error:
But I still have a pb during front initialization
```
polyfills.js:1 Unhandled Promise rejection: Method Promise.prototype.then called on incompatible receiver [object Promise] ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Method Promise.prototype.then called on incompatible receiver [object Promise]
    at then [as __zone_symbol__then] (<anonymous>)
    at polyfills.js:1
    at new t (polyfills.js:1)
    at t.C.t.then (polyfills.js:1)
    at Keycloak.kc.init (keycloak.js:359)
    at app.js:1
    at new t (polyfills.js:1)
    at Function.init (app.js:1)
    at Object.<anonymous> (app.js:1)
    at o (polyfills.js:1) TypeError: Method Promise.prototype.then called on incompatible receiver [object Promise]
    at then [as __zone_symbol__then] (<anonymous>)
    at https://shanoir-ng-nginx/shanoir-ng/polyfills.js:1:88871
    at new t (https://shanoir-ng-nginx/shanoir-ng/polyfills.js:1:87008)
    at t.C.t.then (https://shanoir-ng-nginx/shanoir-ng/polyfills.js:1:88849)
    at Keycloak.kc.init (https://shanoir-ng-nginx/auth/js/keycloak.js:359:27)
    at https://shanoir-ng-nginx/shanoir-ng/app.js:1:113179
    at new t (https://shanoir-ng-nginx/shanoir-ng/polyfills.js:1:87008)
    at Function.init (https://shanoir-ng-nginx/shanoir-ng/app.js:1:113157)
    at Object.<anonymous> (https://shanoir-ng-nginx/shanoir-ng/app.js:1:510568)
    at o (https://shanoir-ng-nginx/shanoir-ng/polyfills.js:1:410)
```

This must be a

**Comment by michaelkain** [comment]
Hi, sorry my mistake. YES, there remains this error where I would require help of the Angular experts -> @Nunien + @jcomedouteau

**Comment by jcomedouteau** [comment]
The bug is known:
https://keycloak.discourse.group/t/javascript-adapter-promise-error-after-upgrade-to-keycloak-11/4200
and corrected
https://github.com/keycloak/keycloak/pull/7430

But this pull request was merged (16 days ago) but not tagged yet => So it is not available for the moment.
https://github.com/keycloak/keycloak/tags

I think we should report this pull request merge.

Needs to be changed too in keycloak.service.ts (see migrating changes https://www.keycloak.org/docs/latest/upgrading/#migration-changes )
```
        return keycloakAuth.init({ onLoad: 'login-required' })
                .then(function(authenticated) {
                    alert(authenticated ? 'authenticated' : 'not authenticated');
                    KeycloakService.auth.loggedIn = true;
                    KeycloakService.auth.authz = keycloakAuth;
                    // Connected user id
                    KeycloakService.auth.userId = keycloakAuth.tokenParsed.userId;
                    KeycloakService.auth.logoutUrl = keycloakAuth.authServerUrl + '/realms/shanoir-ng/protocol/openid-connect/logout?redirect_uri='
                        + AppUtils.LOGOUT_REDIRECT_URL;
                }).catch(function(error) {
                    alert('failed to initialize' + error);
                });
```

**Comment by michaelkain** [comment]
New migration started to version 12.0.1 of Keycloak

**Pull request closed without merging**
