### PR TITLE
New Home Page

### PR DESCRIPTION
**Pull request by Nunien**
Capture d’écran de 2021-04-02 15-33-05

Should be tested : 
* as an admin and a user/expert
* with pending DUA signing
* with pending challenge DUA signing
* with existing jobs

### CODE REVIEW

**Comment by jcomedouteau** [comment]
For the next time, as we stated previously, you should not be developing on your "develop" branch. You should create a branch linked to an issue, and name it shanoir-issue#XXX :)
Anyway, I'm testing it

**Comment by jcomedouteau** [comment]
I'm not fan of sub / exa
image

Maybe just icons ?

**Comment by michaelkain** [comment]
Hi Julien, I think an icon for documentation would be great to on the home page:
- user tutorials (e.g. link to GoogleDoc)
- REST-API connection documentation
- GitHub Wiki link for developers?

**Comment by Nunien** [comment]
@michaelkain 
What google doc user tutorials do we have ?

**Comment by Nunien** [comment]
J'ai trouvé

**Comment by Nunien** [comment]
@jcomedouteau @michaelkain corrections done !

**Comment by jcomedouteau** [comment]
I'm on it !

**Comment by jcomedouteau** [comment]
All is good for me.
I found out something strange, but this is not part of this PR so I'll create a new issue I think.
When the DUA is updated on a study, iwe are not asked to re-sign again the new DUA, I thought it was the current rule.

**Review by jcomedouteau — APPROVED** [review]

**Pull request merged**
