### PR TITLE
performances optimizations in clinical context

### PR DESCRIPTION
**Pull request by julien-louis**
* get subjects by study Id
    * use PostAuthorize instead of PostFilter -> 1 db request instead of n (n subjects)
    * remove useless n request to retrieve subject study tags (already present in the subject study object)
    * move request that get study tags outside the loop : n to 1 calls
* get studies with their centers
    * remove the slow List<Study> findAllWithCenters();
* removed some @EntityGraph as I think it slowed down the request
    * I need to discuss it with @michaelkain to see if I didn't break anything
* removed loops with n db requests to fill children
* had to used "manual" HQL queries instead

### CODE REVIEW

**Comment by julien-louis** [comment]
ok I have to keep findNamesAndCenters

**Comment by LaurentPV** [comment]
The endpoint findAllSubjectsOfStudyId performance is greatly improved : from 2 minutes 45seconds to 6seconds

The endpoint findStudiesNamesAndCenters returns a 500 error for now.

**Comment by julien-louis** [comment]
@LaurentPV  Ok it's fixed. One warning : if the uploader would feature setting tags to the subject at import this fix would break it. But I analyzed that the uploader hasn't got this feature.

**Comment by LaurentPV** [comment]
tested today, everything is ok and performances are improved.

**Review by LaurentPV — APPROVED** [review]
nothing to say about your commits. everything seems ok

**Pull request merged**
