### PR TITLE
Shanoir issue#688 Download name - use study name + subject + exam name

### PR DESCRIPTION
**Pull request by jcomedouteau**

### CODE REVIEW

**Review by michaelkain — COMMENTED** [review]
Code review approved, I will test on my machine

**Comment by michaelkain** [comment]
by the way, I do not see a test report attached to this pull request

**Comment by jcomedouteau** [comment]
For my other pull request,I thought it was linked to the way we were zipping the files.
Unzipping actually works on linux, but not on mac nor windows.
I'll check and write a proper test report !

**Comment by michaelkain** [comment]
Hi Jean-Come, thx for your fast answer, but just an idea, at the moment I can not verify it as my local dev Shanoir has decided to crash right now, but maybe as I am using SoapUI and generate very long UUIDs e.g. for the study and subject names, maybe the file names are too long inside the zip? just an idea to help you analyse the issue

**Comment by jcomedouteau** [comment]
How to test this pull request:
- Download multiple datasets from solr search or study detail
- Check that the archive contains a folder with
1) study name
2) subject name
3) Exam id
4) Exam comment

**Comment by jcomedouteau** [comment]
@michaelkain Maybe it's linked to the name of the study / subject / exam comment that you tried to download ? I guess we need to protect this.

**Comment by michaelkain** [comment]
@jcomedouteau Hi Jean-Come, there is a bigger error. I changed my study+subject naming to shorter version, very short, and removed any special character and still the download file can not be opened.

**Comment by jcomedouteau** [comment]
It seems to be linked to the way we zip the files but I'm quite skeptical, we didn't changed many things

**Comment by jcomedouteau** [comment]
I found out what was the problem, it is linked to our progress bar development..

**Comment by jcomedouteau** [comment]
@michaelkain Tests are successful, you can review this PR.

**Review by michaelkain — APPROVED** [review]

**Comment by michaelkain** [comment]
Hi Jean-Come, good news: I tested successfully on the qualif and now the file name is back to DatasetsTimeStamp.zip, what is much much better, as files are not samed the same way to always directly save them. I used SoapUI to import one serie and download this serie + other ones and it worked.

**Pull request merged**
