### PR TITLE
Shanoir-issue#970 Progress bar for upload + error when file too big

### PR DESCRIPTION
**Pull request by jcomedouteau**
1) Upload dicom file and see the progress
2) Upload a file with size  > 5Gb and see the error

### CODE REVIEW

**Comment by Nunien** [comment]
@jcomedouteau 
Do you know what takes time after the uploading is 100% ? Is it the processing of it by the backend service ?

**Comment by jcomedouteau** [comment]
Yes it's the processing that takes time. We could imagine a "Processing data..." message when the upload is at 100% ?

**Comment by Nunien** [comment]
> Yes it's the processing that takes time. We could imagine a "Processing data..." message when the upload is at 100% ?

Yes, but it can be done in another development, this pr is an improvement.

**Comment by Nunien** [comment]
> Can you check the error that comes back from the backend ?

Yes sorry it's 413 Request Entity Too Large

**Comment by jcomedouteau** [comment]
I corrected it @Nunien

**Pull request merged**
