### PR TITLE
Shanoir issue#487 download datasets

### PR DESCRIPTION
**Pull request by jcomedouteau**

### CODE REVIEW

**Review by michaelkain — CHANGES_REQUESTED** [review]
Hi Jean-Come, I have fear that the download of an entire study could crash the server, e.g. we have a study that contains 3.000 patients. What do you think? In the code your limit is only for multi-downloads. Cheers, Michael

**Comment by jcomedouteau** [comment]
That's totally true !

**Comment by michaelkain** [comment]
I am on it.

**Comment by michaelkain** [comment]
Great job! I have tested on my machine. Single file download, multiple, 50 or more, everything worked fine. I will accept the PR for the 22.09., great. Only one point to optimise: the case of downloading one empty dataset could be optimised, as it returns a zip file, that can not be opened.

**Pull request merged**
