### PR TITLE
Appning branch

### PR DESCRIPTION
**Pull request by jcomedouteau**
Too much things in it
=> Preclinical
=> EEG
=> BIDS

### CODE REVIEW

**Comment by jcomedouteau** [comment]
@michaelkain This is the pull request to merge.

**Comment by michaelkain** [comment]
Hi Jean-Come, excellent, mvn install is already passing without a problem!
We will have to document: _docker image import dicomifier_ws.img_ and share
the image dicomifier_ws.img with the others OR have a dockerhub providing the image.

**Comment by michaelkain** [comment]
With the cmd docker-compose up, I get an error:
Recreating preclinical-bruker2dicom ... error
ERROR: for preclinical-bruker2dicom  Cannot start service preclinical-bruker2dicom: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python3\": executable file not found in $PATH": unknown
I hope it took the right version of the image...

**Comment by jcomedouteau** [comment]
Did you manage to resolve the problem ? Do you have python 3 on your computer ?

**Comment by michaelkain** [comment]
Hi Jean-Come, I have Python 2.7.10 on my machine, but all this should happen inside the containers and my version should not matter?

**Comment by michaelkain** [comment]
Which img do you use from dicomifier, maybe I have another one?
Bildschirmfoto 2020-05-07 um 14 21 46

**Comment by jcomedouteau** [comment]
I'm using dicomifier.ws.img (not v2 maybe ?) Do you want the archive ?

**Comment by jcomedouteau** [comment]
I think it's this one
https://hub.docker.com/r/lamyj/dicomifier

with the following dockerFile:
FROM debian:stable
LABEL maintainer="Julien Lamy <lamy@unistra.fr>"
RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y gnupg software-properties-common wget && \
  wget -O - http://dl.bintray.com/lamyj/generic/gpg.key | apt-key add - && \
  add-apt-repository "deb http://dl.bintray.com/lamyj/generic/apt $(lsb_release -cs) main" && \
  apt-get update && \
  apt-get install --no-install-recommends -y dicomifier-cli

wasn't this commit anywhere ?

**Comment by michaelkain** [comment]
I will check. MS Studies is not running up because of:
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name '**rabbitMQConfiguration**' for bean class [org.shanoir.ng.shared.configuration.RabbitMQConfiguration] conflicts with existing, non-compatible bean definition of same name and class [org.shanoir.ng.configuration.amqp.RabbitMQConfiguration]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:320)

**Comment by michaelkain** [comment]
Hi, I found the solution, please change in the docker-compose.yml to:
  preclinical-bruker2dicom:
    container_name: preclinical-bruker2dicom
    image: **lamyj/dicomifier**
    command: ["python3", "/root/run.py"]
It failed the first run, but now it works. The problem was when you use **dicomifier.ws**, it searches only locally for the image, what can vary, with using **lamyj/dicomifier** it downloads from dockerhub. Now it runs up.

**Comment by michaelkain** [comment]
I did not know, that Julien had already put it to dockerhub, what is a good thing.

**Comment by jcomedouteau** [comment]
I'm checking the RabbitMQConfig problem, that's weird.

**Comment by michaelkain** [comment]
Hi, excellent, MS Studies is working and running now. On the other hand no import is working, neither with the web GUI nor with ShUp. Let's discuss Monday, how we proceed. I guess it has to do something with the tasks, as they do not work for display, just guessing. MS Import finishes well, but MS Datasets logs this: 2020-05-07 15:27:58.598 ERROR 1 --- [SimpleAsyncTaskExecutor-1] .s.n.i.c.DatasetAcquisitionApiController : null
java.lang.NullPointerException: null
	at org.shanoir.ng.utils.KeycloakUtil.getKeycloakSecurityContext(KeycloakUtil.java:140)
	at org.shanoir.ng.utils.KeycloakUtil.getTokenUserId(KeycloakUtil.java:102)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:102)
What is strange, because I think I solved this when using RabbitMQ between ms import and ms datasets.

**Comment by jcomedouteau** [comment]
I'm on it. I should have tested more, I'm really sorry for this !

**Comment by michaelkain** [comment]
No problem at all, we are much better than what I was expecting with such a big merge! And it is related to my change to RabbitMQ (ms import -> ms datasets), the token is not present anymore and the code is expecting it, so this is more a feature fusion thing than a bug. Maybe we have to put the userId into the ImportJob to solve this? to see

**Comment by jcomedouteau** [comment]
Yes, I'm trying to see if we can travel with a security context with rabbitMQ, but it doesn't seem easy to do.
When do you want to discuss this ?

**Comment by jcomedouteau** [comment]
I have a new problem, quite surprising:
Unexpected error during the import: failed to lazily initialize a collection of role: org.shanoir.ng.examination.model.Examination.datasetAcquisitions, could not initialize proxy - no Session

As if the hibernate session was not active

**Comment by jcomedouteau** [comment]
This is linked to BIDS folder, let's ignore this for the moment, I'll do it later.
I pushed a change to set the user ID in the rabbitMQ message headers.

**Comment by michaelkain** [comment]
Hi Jean-Come, I pulled 5 minutes ago. I did a mvn clean. Now I have an error with mvn install:
[INFO] shanoir-ng-datasets ................................ FAILURE [01:01 min]
Running org.shanoir.ng.datasetacquisition.service.**ImporterServiceTest**
16:43:48.628 [main] ERROR org.shanoir.ng.importer.service.ImporterService - **Error during import for exam: 1 : {}
java.lang.NullPointerException: null**
	at org.shanoir.ng.importer.service.ImporterService.**createAllDatasetAcquisition**(ImporterService.java:109)
	at org.shanoir.ng.importer.service.ImporterService$$EnhancerByMockitoWithCGLIB$$4b90399d.CGLIB$createAllDatasetAcquisition$3(<generated>), sorry!

**Comment by michaelkain** [comment]
Let me know, if you get tired of this and I accept and we fix on develop.

**Comment by jcomedouteau** [comment]
Im' on it !

**Comment by jcomedouteau** [comment]
Can you try now ? (I wasn't able to launch the test locally as i'm switching branches..)

**Comment by michaelkain** [comment]
sorry, I was fixing EnhancedMR, I try tomorrow morning.

**Comment by jcomedouteau** [comment]
Cheers ! :)

**Pull request merged**
